#!/bin/bash

# Mayyam Remote Bootstrapper
# This script installs and starts Mayyam in production mode
# Usage: curl -sSL https://raw.githubusercontent.com/sumitharajan/mayyam/main/scripts/install.sh | bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}==========================================${NC}"
echo -e "${BLUE}        Mayyam Installation Script        ${NC}"
echo -e "${BLUE}==========================================${NC}"

# 1. Check Prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Please install Docker from https://docs.docker.com/get-docker/"
    exit 1
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Please install Docker Compose from https://docs.docker.com/compose/install/"
    exit 1
fi

COMPOSE_CMD="docker-compose"
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
fi

echo -e "${GREEN}✓ Docker is installed${NC}"

# 2. Setup Directory
INSTALL_DIR="${HOME}/mayyam-deployment"
echo -e "\n${YELLOW}Setting up Mayyam in ${INSTALL_DIR}...${NC}"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# 3. Download configurations
echo -e "\n${YELLOW}Downloading configuration files...${NC}"

REPO_RAW_URL="https://raw.githubusercontent.com/sumitharajan/mayyam/main"

curl -sSL -o docker-compose.prod.yml "${REPO_RAW_URL}/docker-compose.prod.yml" || {
    echo -e "${RED}Failed to download docker-compose.prod.yml${NC}"
    exit 1
}

# 4. Prompt for secure defaults or generate them
if [ ! -f .env ]; then
    echo -e "\n${YELLOW}Generating secure configuration (.env)...${NC}"
    
    # Generate random passwords if `openssl` is available, else fallback to hardcoded
    if command -v openssl &> /dev/null; then
        DB_PASSWORD=$(openssl rand -hex 16)
        MYSQL_PASSWORD=$(openssl rand -hex 16)
        ENCRYPTION_KEY=$(openssl rand -hex 32)
    else
        DB_PASSWORD="mayyam_pg_$(date +%s)"
        MYSQL_PASSWORD="mayyam_mysql_$(date +%s)"
        ENCRYPTION_KEY="mayyam_enc_$(date +%s)"
    fi

    cat > .env << EOL
# Auto-generated by Mayyam install.sh
DB_PASSWORD=${DB_PASSWORD}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
EOL
    echo -e "${GREEN}✓ Created secure .env file${NC}"
else
    echo -e "${GREEN}✓ using existing .env file${NC}"
fi

# 5. Start the application
echo -e "\n${YELLOW}Starting Mayyam services...${NC}"
$COMPOSE_CMD -f docker-compose.prod.yml pull
$COMPOSE_CMD -f docker-compose.prod.yml up -d

# 6. Success message
echo -e "\n${GREEN}==========================================${NC}"
echo -e "${GREEN}  Mayyam has been successfully started!   ${NC}"
echo -e "${GREEN}==========================================${NC}"
echo -e ""
echo -e "The application is starting up. It may take a minute or two for the database"
echo -e "migrations to complete and the web server to become ready."
echo -e ""
echo -e "🌐 Access the application at: ${BLUE}http://localhost${NC} (or your server's IP)"
echo -e ""
echo -e "To view logs, run:\n  ${YELLOW}cd $INSTALL_DIR && $COMPOSE_CMD -f docker-compose.prod.yml logs -f mayyam-prod${NC}"
echo -e ""
echo -e "To stop the application, run:\n  ${YELLOW}cd $INSTALL_DIR && $COMPOSE_CMD -f docker-compose.prod.yml down${NC}"
